version: "3"

services:
  mariadb:
    image: mariadb:10.7
    environment:
      # Create a default database for osTicket
      MARIADB_DATABASE: osticket
      MARIADB_USER: osticket
      # Set through environment file
      MARIADB_ROOT_PASSWORD:
      # Set through environment file
      MARIADB_PASSWORD:
  osticket:
    # Use a custom image, especially optimized for production
    build:
      context: .
      dockerfile: ./docker/production/Dockerfile
      args:
        - SERVER_NAME
    depends_on:
      - mariadb
    volumes:
      - ost-config:/config

volumes:
  ost-config:
